### ISSUE TITLE
Example for use of odoo.backupdb

### ISSUE THREAD

**Issue by HavardLine** [nmbooker/oekit#5]
Hi There
I have tried to use odoo.backupdb without success.

Are there any examples for use of this function?
What is the output format?

Thanks,
Håvard

**Comment by Nick-OpusVL** [comment]
```
  odoo.backupdb --admin-password adminpass -u http://odooserver:8069 -o mydb.zip  mydb
```

You may need to play with whether to put a trailing forward-slash at the end of the URL.

With any luck the above should log into the database manager for the Odoo running on odooserver port 8069 with password adminpass (note this is the password for the database manager, and not the password for the admin user of the database itself), and download a backup of the mydb database (including database and filestore) and putting it in the zip file mydb.zip in your current directory.

Without -o it will output the zip file on STDOUT, and without -u it will try to use the OE_CLIENT_URL environment variable.

Please let me know whether that example worked (with modifications to suit your environment of course), and I'll put it into the documentation.

**Comment by Nick-OpusVL** [comment]
I should note it's equivalent to logging into the database manager and clicking the button to get a backup in zip format.

**Comment by HavardLine** [comment]
Perfect!

Thanks Nick-OpusVL

**Comment by Nick-OpusVL** [comment]
No problem.  I've added the example and explanation above to the README file.
